### ISSUE TITLE
Migrations are not shipped with the library

### ISSUE THREAD

**Issue by 0x4bs3nt** [brianrisk/exceptbot#1]
Hello Brian,

when your library is dependant on a database, has model, is creating new tables and relies on the user to migrate these changes, you should also ship the migrations for those models.

It can cause issues especially if you do not have a migrations directory with a `__init__.py` file, forcing the user to specifically create migrations files using `python manage.py makemigrations exceptbot`.

See [Stackoverflow](https://stackoverflow.com/questions/38277191/how-do-i-source-control-migrations-for-3rd-party-django-apps/38277776#38277776) . Shouldn't be a big issue to fix.

Best regards,
Jan Tumpa.

**Comment by brianrisk** [comment]
Jan, thank you for this -- I've updated the gitignore to no longer exclude these files; added those files; incremented the library version and pushed.  I hope it works for you now!

**Comment by 0x4bs3nt** [comment]
You might also wanna adjust your README for the running migrations part, specifically this line:
`python3 manage.py makemigrations exceptbot`.

Otherwise, the changes look good, thanks.
